version: "3"
services:
  nginx: 
    ports:
      - "80:80"

  node-app:
  # swarm configs
    deploy:
      replicas: 8
      restart_policy: 
        conditions: any
      update_config: 
        parallelism: 2
        delay: 15s
  # app configs
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
    # env_file:
    #   - ./.env