version: "3"
services:
  nginx: 
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: nginx
    ports: 
      - "3000:80"
      # this is where the nginx server is located
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-app:
    build: .
    image: boubamahir/node-app
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_IP=mongo
      - SESSION_SECRET=${SESSION_SECRET}
      
      #here we say start mongo container first because our node app depends on it
    depends_on:
      - mongo
      - redis
    # env_file:
    #   - ./.env
  # another service
  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      
      #save our db
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    environment:
      - REDIS_URL='redis://redis:6379'
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
    ports:
    - "6379:6379"

volumes:
  mongo-db:




  # mongo-express:
  #   image: mongo-express
  #   restart: unless-stopped
  #   container_name: mexpress
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=
  #     - ME_CONFIG_MONGODB_SERVER=mongo
